// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	product.proto

It has these top-level messages:
	Product
	ListProductsResponse
	GetProductRequest
	CreateProductRequest
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/golang/protobuf/ptypes/empty"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Product struct {
	Id               *string                    `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name             *string                    `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description      *string                    `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Attributes       []string                   `protobuf:"bytes,4,rep,name=attributes" json:"attributes,omitempty"`
	Images           []string                   `protobuf:"bytes,5,rep,name=images" json:"images,omitempty"`
	CreateTime       *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *Product) Reset()                    { *m = Product{} }
func (m *Product) String() string            { return proto1.CompactTextString(m) }
func (*Product) ProtoMessage()               {}
func (*Product) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Product) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *Product) GetAttributes() []string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Product) GetImages() []string {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *Product) GetCreateTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

type ListProductsResponse struct {
	Products         []*Product `protobuf:"bytes,1,rep,name=products" json:"products,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *ListProductsResponse) Reset()                    { *m = ListProductsResponse{} }
func (m *ListProductsResponse) String() string            { return proto1.CompactTextString(m) }
func (*ListProductsResponse) ProtoMessage()               {}
func (*ListProductsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListProductsResponse) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type GetProductRequest struct {
	Id               *string `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetProductRequest) Reset()                    { *m = GetProductRequest{} }
func (m *GetProductRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetProductRequest) ProtoMessage()               {}
func (*GetProductRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetProductRequest) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type CreateProductRequest struct {
	Product          *Product `protobuf:"bytes,1,req,name=product" json:"product,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CreateProductRequest) Reset()                    { *m = CreateProductRequest{} }
func (m *CreateProductRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreateProductRequest) ProtoMessage()               {}
func (*CreateProductRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateProductRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func init() {
	proto1.RegisterType((*Product)(nil), "proto.Product")
	proto1.RegisterType((*ListProductsResponse)(nil), "proto.ListProductsResponse")
	proto1.RegisterType((*GetProductRequest)(nil), "proto.GetProductRequest")
	proto1.RegisterType((*CreateProductRequest)(nil), "proto.CreateProductRequest")
}

func init() { proto1.RegisterFile("product.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4d, 0x6b, 0xeb, 0x30,
	0x10, 0x8c, 0x9d, 0xaf, 0x97, 0xf5, 0x4b, 0xe0, 0x2d, 0x21, 0x08, 0x07, 0x5e, 0x8d, 0x7b, 0x31,
	0x3d, 0x38, 0x90, 0x53, 0xa1, 0x50, 0xfa, 0x41, 0xe8, 0xa5, 0x87, 0x62, 0x7a, 0x2f, 0x4e, 0xbc,
	0x0d, 0x82, 0x3a, 0x52, 0x2d, 0xf9, 0xd0, 0xff, 0xd7, 0x6b, 0xff, 0x53, 0x89, 0x24, 0x37, 0x69,
	0x92, 0x93, 0xad, 0x99, 0xd1, 0xec, 0xec, 0x20, 0x18, 0xca, 0x4a, 0x14, 0xf5, 0x4a, 0xa7, 0xb2,
	0x12, 0x5a, 0x60, 0xd7, 0x7c, 0xc2, 0xb3, 0xb5, 0x10, 0xeb, 0x37, 0x9a, 0x99, 0xd3, 0xb2, 0x7e,
	0x9d, 0x69, 0x5e, 0x92, 0xd2, 0x79, 0x29, 0xad, 0x2e, 0x9c, 0x1e, 0x0a, 0xa8, 0x94, 0xfa, 0xc3,
	0x92, 0xf1, 0xa7, 0x07, 0xfd, 0x27, 0x6b, 0x8b, 0x23, 0xf0, 0x79, 0xc1, 0xbc, 0xc8, 0x4b, 0x06,
	0x99, 0xcf, 0x0b, 0x44, 0xe8, 0x6c, 0xf2, 0x92, 0x98, 0x6f, 0x10, 0xf3, 0x8f, 0x11, 0x04, 0x05,
	0xa9, 0x55, 0xc5, 0xa5, 0xe6, 0x62, 0xc3, 0xda, 0x86, 0xda, 0x87, 0xf0, 0x3f, 0x40, 0xae, 0x75,
	0xc5, 0x97, 0xb5, 0x26, 0xc5, 0x3a, 0x51, 0x3b, 0x19, 0x64, 0x7b, 0x08, 0x4e, 0xa0, 0xc7, 0xcb,
	0x7c, 0x4d, 0x8a, 0x75, 0x0d, 0xe7, 0x4e, 0x78, 0x05, 0xc1, 0xaa, 0xa2, 0x5c, 0xd3, 0xcb, 0x76,
	0x01, 0xd6, 0x8b, 0xbc, 0x24, 0x98, 0x87, 0xa9, 0x0d, 0x9f, 0x36, 0xe1, 0xd3, 0xe7, 0x66, 0xbb,
	0x0c, 0xac, 0x7c, 0x0b, 0xc4, 0x77, 0x30, 0x7e, 0xe4, 0x4a, 0xbb, 0x4d, 0x54, 0x46, 0x4a, 0x8a,
	0x8d, 0x22, 0xbc, 0x80, 0x3f, 0xae, 0x34, 0xc5, 0xbc, 0xa8, 0x9d, 0x04, 0xf3, 0x91, 0xb5, 0x4a,
	0x9d, 0x34, 0xfb, 0xe1, 0xe3, 0x73, 0xf8, 0xf7, 0x40, 0x8d, 0x45, 0x46, 0xef, 0x35, 0xa9, 0x5d,
	0x27, 0xbe, 0xed, 0x24, 0xbe, 0x81, 0xf1, 0xbd, 0x19, 0x7b, 0xa0, 0x4b, 0xa0, 0xef, 0x8c, 0x8c,
	0xf8, 0x78, 0x4e, 0x43, 0xcf, 0xbf, 0x3c, 0x00, 0x07, 0xde, 0x4a, 0x8e, 0x97, 0x00, 0xbb, 0xa9,
	0xc8, 0xdc, 0xad, 0xa3, 0x20, 0xe1, 0x81, 0x5f, 0xdc, 0xc2, 0x6b, 0x18, 0xfe, 0x8a, 0x82, 0x53,
	0x27, 0x39, 0x15, 0xf0, 0xc4, 0xfd, 0x05, 0xfc, 0xdd, 0xef, 0x0c, 0x27, 0x47, 0x5d, 0x2f, 0xb6,
	0x0f, 0x25, 0x6c, 0x6c, 0x4f, 0x15, 0x1c, 0xb7, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x39,
	0x45, 0x8d, 0x96, 0x02, 0x00, 0x00,
}
